import Head from "next/head";
import Card from "./../components/Card/card.js";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navbar/navigation";
import TabList from "../components/Card/Tabs/tabList";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Navigation></Navigation>
      </header>
      <main className={styles.main}>
        <Card>
          <TabList></TabList>
        </Card>
      </main>
    </div>
  );
}
