import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navbar/navigation";
import TabList from "../components/Card/Tabs/tabList";
import QuizView from "./../components/StartQuiz/quizView";
import Question from "../components/StartQuiz/QuestionsView/questionPage";
import Card from "./../components/Card/card";
import ConfirmLog from "../components/StartQuiz/confirmLog";
import FeedBack from "./../components/FeedbackForm/Feedback";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}></header>
      <main className={styles.main}>
        <FeedBack></FeedBack>
      </main>
    </div>
  );
}
